GlobalList =
{
    { TRUE, FALSE, TRUE },
    { TRUE, FALSE, TRUE },
    { TRUE, FALSE, TRUE },
    { TRUE, FALSE, TRUE },
    { TRUE, FALSE, TRUE },
    { TRUE, FALSE, TRUE },
    { TRUE, FALSE, TRUE },
}

GlobalList2 =
{
    [0] = { TRUE, FALSE, TRUE },
    [1] = { TRUE, FALSE, TRUE },
    [2] = { TRUE, FALSE, TRUE },
    [3] = { TRUE, FALSE, TRUE },
    [4] = { TRUE, FALSE, TRUE },
    [5] = { TRUE, FALSE, TRUE },
    [6] = { TRUE, FALSE, TRUE },
}

GlobalList3 =
{
    [0] = { TRUE, FALSE, TRUE },
    { TRUE, FALSE, TRUE },
    { TRUE, FALSE, TRUE },
    { TRUE, FALSE, TRUE },
    { TRUE, FALSE, TRUE },
    { TRUE, FALSE, TRUE },
    { TRUE, FALSE, TRUE },
}

MagicPutOppositeWeapon = {[0] = {TRUE, TRUE, TRUE}, {FALSE, FALSE, TRUE}, {FALSE, FALSE, TRUE}, {FALSE, FALSE, TRUE}, {FALSE, FALSE, TRUE}, {TRUE, TRUE, TRUE}, {TRUE, TRUE, TRUE}, {TRUE, TRUE, TRUE}, {FALSE, FALSE, TRUE}, {FALSE, FALSE, TRUE}, {FALSE, FALSE, TRUE}, {FALSE, FALSE, TRUE}, {FALSE, FALSE, TRUE}, {FALSE, FALSE, TRUE}, {TRUE, TRUE, TRUE}, {TRUE, TRUE, TRUE}, {FALSE, FALSE, TRUE}, {FALSE, FALSE, TRUE}, {FALSE, FALSE, TRUE}, {FALSE, FALSE, TRUE}, {FALSE, FALSE, TRUE}, {FALSE, FALSE, TRUE}, {TRUE, TRUE, TRUE}, {FALSE, FALSE, TRUE}, {TRUE, TRUE, TRUE}, {FALSE, FALSE, TRUE}, {FALSE, FALSE, TRUE}, {FALSE, FALSE, TRUE}, {FALSE, FALSE, TRUE}, {FALSE, FALSE, TRUE}, {FALSE, FALSE, TRUE}, {FALSE, FALSE, TRUE}, {FALSE, FALSE, TRUE}, {FALSE, FALSE, TRUE}, {FALSE, FALSE, TRUE}, {FALSE, FALSE, TRUE}, {FALSE, FALSE, TRUE}, {FALSE, FALSE, TRUE}, {FALSE, FALSE, TRUE}, {FALSE, FALSE, TRUE}, {FALSE, FALSE, TRUE}, {FALSE, FALSE, TRUE}, {FALSE, FALSE, TRUE}, {FALSE, FALSE, TRUE}, {FALSE, FALSE, TRUE}, {FALSE, FALSE, TRUE}, {FALSE, FALSE, TRUE}, {FALSE, FALSE, TRUE}, {TRUE, TRUE, TRUE}, {FALSE, FALSE, TRUE}, {TRUE, TRUE, TRUE}, {TRUE, TRUE, TRUE}, {FALSE, FALSE, TRUE}, {FALSE, FALSE, TRUE}, {TRUE, TRUE, TRUE}, {TRUE, TRUE, TRUE}, {TRUE, TRUE, TRUE}, {TRUE, TRUE, TRUE}, {TRUE, TRUE, TRUE}, {FALSE, FALSE, TRUE}, {TRUE, TRUE, TRUE}, {FALSE, FALSE, TRUE}, {FALSE, FALSE, TRUE}, {FALSE, FALSE, TRUE}, {FALSE, FALSE, TRUE}, {FALSE, FALSE, TRUE}, {FALSE, FALSE, TRUE}, {TRUE, TRUE, TRUE}, {FALSE, FALSE, TRUE}, {FALSE, FALSE, TRUE}, {FALSE, FALSE, TRUE}, {TRUE, TRUE, TRUE}, {FALSE, FALSE, TRUE}, {FALSE, FALSE, TRUE}, {TRUE, TRUE, TRUE}, {FALSE, FALSE, TRUE}, {FALSE, FALSE, TRUE}, {FALSE, FALSE, TRUE}, {FALSE, FALSE, TRUE}, {FALSE, FALSE, TRUE}, {FALSE, FALSE, TRUE}, {TRUE, TRUE, TRUE}, {TRUE, TRUE, TRUE}, {FALSE, FALSE, TRUE}, {FALSE, FALSE, TRUE}, {FALSE, FALSE, TRUE}, {TRUE, TRUE, TRUE}, {TRUE, TRUE, TRUE}, {TRUE, TRUE, TRUE}, {TRUE, TRUE, TRUE}, {TRUE, TRUE, TRUE}, {TRUE, TRUE, TRUE}, {FALSE, FALSE, TRUE}, {FALSE, FALSE, TRUE}, {FALSE, FALSE, TRUE}, {FALSE, FALSE, TRUE}, {FALSE, FALSE, TRUE}, {FALSE, FALSE, TRUE}, {TRUE, TRUE, TRUE}, {FALSE, FALSE, TRUE}, {FALSE, FALSE, TRUE}, {FALSE, FALSE, TRUE}, {TRUE, TRUE, TRUE}, {FALSE, FALSE, TRUE}, {FALSE, FALSE, TRUE}, {TRUE, TRUE, TRUE}, {FALSE, FALSE, TRUE}, {FALSE, FALSE, TRUE}, {FALSE, FALSE, TRUE}, {FALSE, FALSE, TRUE}, {FALSE, FALSE, TRUE}, {FALSE, FALSE, TRUE}, {FALSE, FALSE, TRUE}, {FALSE, FALSE, TRUE}, {FALSE, FALSE, TRUE}, {TRUE, TRUE, TRUE}, {TRUE, TRUE, TRUE}, {FALSE, FALSE, TRUE}, {FALSE, FALSE, TRUE}, {FALSE, FALSE, TRUE}, {TRUE, TRUE, TRUE}, {TRUE, TRUE, TRUE}, {TRUE, TRUE, TRUE}, {TRUE, TRUE, TRUE}, {FALSE, FALSE, TRUE}, {FALSE, FALSE, TRUE}, {FALSE, FALSE, TRUE}, {FALSE, FALSE, TRUE}, {FALSE, FALSE, TRUE}, {FALSE, FALSE, TRUE}, {FALSE, FALSE, TRUE}, {FALSE, FALSE, TRUE}, {FALSE, FALSE, TRUE}, {FALSE, FALSE, TRUE}, {FALSE, FALSE, TRUE}, {FALSE, FALSE, TRUE}, {FALSE, FALSE, TRUE}, {FALSE, FALSE, TRUE}, {FALSE, FALSE, TRUE}, {FALSE, FALSE, TRUE}, {FALSE, FALSE, TRUE}, {FALSE, FALSE, TRUE}, {FALSE, FALSE, TRUE}, {FALSE, FALSE, TRUE}, {FALSE, FALSE, TRUE}, {FALSE, FALSE, TRUE}, {FALSE, FALSE, TRUE}, {FALSE, FALSE, TRUE}, {FALSE, FALSE, TRUE}, {FALSE, FALSE, TRUE}, {FALSE, FALSE, TRUE}}